Inline script

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -22,7 +22,38 @@ runs:
       shell: bash
       run: |
         git fetch origin
-        git_command=$(./src/commitlog.sh --branch "${{ inputs.branch-name }}")
+
+        current_branch=${{ inputs.branch-name }}
+
+        # Define the git format
+        commit_log_format="--pretty=format:\"%h - %an - %ad - %s\" --date=default"
+
+        if [ -z "$current_branch" ]; then
+          echo "Error: Missing current branch name." >&2
+          exit 1
+        fi
+
+        # Get a list of all tags sorted by tagger date
+        tags_sorted_by_date=$(git tag --sort='-creatordate')
+
+        echo "::debug::Tags sorted by date $tags_sorted_by_date"
+        # Find the previous tag based on the tagger date
+        previous_tag=""
+        for tag in $tags_sorted_by_date; do
+          echo "::debug::Tag $tag"
+          if git branch --contains $tag | grep -q -- "$current_branch"; then
+            previous_tag=$tag
+            break
+          fi
+        done
+
+        # Calculate the commit log
+        if [ -z "$previous_tag" ]; then
+          git_command="git log $commit_log_format"
+        else
+          git_command="git log $previous_tag..$current_branch $commit_log_format"
+        fi
+
         echo "::debug::Git command $git_command"
         commit_log=$(eval $git_command)
         echo "::debug::Commig log $commit_log"
