Restore old script

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -25,18 +25,24 @@ runs:
 
         ##commit_log=$(./src/commitlog.sh "${{ inputs.branch-name }}")
 
+        git fetch --tags
+        current_branch=${{ inputs.branch-name }}
+        
         # Define the git format
         commit_log_format="--pretty=format:\"%h - %ad - %an - %s\n\" --date=format:'%d %b %Y'"
-
+        if [ -z "$current_branch" ]; then
+          echo "Error: Missing current branch name." >&2
+          exit 1
+        fi
+        
         # Get a list of all tags sorted by tagger date
         tags_sorted_by_date=$(git tag --sort='-creatordate')
-
+        
         # Define the git commands
-        git_current_commit="$(git rev-parse ${{ inputs.branch-name }})"
-
+        git_current_commit="$(git rev-parse $current_branch)"
+        
         # Find the previous tag based on the tagger date
         previous_tag=""
-
         for tag in $tags_sorted_by_date; do
           tag_commit="$(git rev-parse $tag)"
           if [ "$tag_commit" != "$git_current_commit" ]; then
@@ -44,20 +50,15 @@ runs:
             break
           fi
         done
-
-
+        
+      
         # Calculate the commit log
         if [ -z "$previous_tag" ]; then
           git_command="git log $commit_log_format"
         else
-          git_command="git log $previous_tag..${{ inputs.branch-name }} $commit_log_format"
+          git_command="git log $previous_tag..$current_branch $commit_log_format"
         fi
-
-
-        echo $git_command
-        commit_log=$(eval $git_command)
         
-        echo $commit_log
         echo 'COMMIT_LOG<<EOF' >> $GITHUB_OUTPUT
         echo $commit_log >> $GITHUB_OUTPUT
         echo 'EOF' >> $GITHUB_OUTPUT
